Model:
  patch_size: 16
  image_size: 224

Training:
  data_path: /data/datasets/downsampled-open-images-v4/256px/train
  annotations_path: /data/datasets/downsampled-open-images-v4/256px/annotations
  batch_size: 32
  grad_accumulation_steps: 128
  learning_rate: 3e-3
  warmup_steps: 10000
  epochs: 100
  num_samples: 1700000
  log_interval: 10
