Model:
  patch_size: 16
  image_size: 256

Training:
  data_path: /data/datasets/downsampled-open-images-v4/256px/train
  annotations_path: /data/datasets/downsampled-open-images-v4/256px/annotations
  batch_size: 16
  grad_accumulation_steps: 256
  learning_rate: 1e-3
  warmup_steps: 1000
  epochs: 10
  num_samples: 1500000
  log_interval: 10
